force-app/main/default/objects/Budget__c/Budget__c.object-meta.xml
<CustomObject>
    <label>Budget</label>
    <nameField>
        <label>Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budget</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Budget__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>Budget</relationshipLabel>
    <relationshipName>Budget</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Count_of_bugets__c.field-meta.xml
<CustomField>
    <fullName>Count_of_bugets__c</fullName>
    <label>Count of bugets</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Current_Company__c.field-meta.xml
<CustomField>
    <fullName>Current_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>Employee</relationshipLabel>
    <relationshipName>Employee</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CompanyTriggerHandler.cls
public with sharing class CompanyTriggerHandler {
    public void onAfterUpdate(Map<Id,Company__c> newMap){
        Set<Id> budgetIds = new Set<Id>();
        for (Budget__c budgets : [SELECT Id FROM Budget__c WHERE Company__c IN :newMap.values()]) {
            budgetIds.add(budgets.Id);
        }
        
        List<Employee__c> updateList = [SELECT Count_of_bugets__c FROM Employee__c WHERE Current_Company__c IN (SELECT Company__c FROM Budget__c WHERE ID IN :budgetIds)];
        for (Employee__c emp : updateList) {
            List<Budget__c> tempList = [SELECT Id FROM Budget__c WHERE Company__c IN (SELECT Current_Company__c FROM Employee__c WHERE Id =: emp.Id)];
            emp.Count_of_bugets__c = tempList.size();
        }

        if (!updateList.isEmpty()) {
            update updateList;
        }
    }
}