force-app/main/default/objects/Budget__c/Budget__c.object-meta.xml
<CustomObject>
    <label>Budget</label>
    <nameField>
        <label>Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budget</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Budget__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>Budget</relationshipLabel>
    <relationshipName>Budget</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/Head_of_Company__c.field-meta.xml
<CustomField>
    <fullName>Head_of_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Head of Company</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Company</relationshipLabel>
    <relationshipName>Company</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Count_of_bugets__c.field-meta.xml
<CustomField>
    <fullName>Count_of_bugets__c</fullName>
    <label>Count of bugets</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BudgetScheduleBatch.cls
public class BudgetScheduleBatch implements Schedulable, Database.Batchable<SObject> {

    String query = 'SELECT Id FROM ';

    public void BudgetSheduleBatch(){
        this.query += 'Budget__c';
    }

    public void execute(SchedulableContext sc){
        Database.executeBatch(new BudgetScheduleBatch());   
    }

    public Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext bc, List<Budget__c> scope){
        Set<Id> setOfCompaniesId = new Set<Id>();
        for (Budget__c budget : [SELECT Company__c FROM Budget__c WHERE Id IN: scope]) {
            setOfCompaniesId.add(budget.Company__c);
        }
        List<AggregateResult> aggrRes = [SELECT COUNT(Id) coun, Company__r.Head_of_Company__c testId                                                FROM Budget__c
                                        WHERE Company__c IN :setOfCompaniesId
                                        AND Active__c = true
                                        GROUP BY Company__r.Head_of_Company__c];
        List<Employee__c> updateEmployeeList = new List<Employee__c>();

        for (AggregateResult aggr_i : aggrRes) {
            updateEmployeeList.add(new Employee__c(Id = (Id)(aggr_i.get('testId')), Count_of_bugets__c = (Decimal)aggr_i.get('coun')));
        }
        if (!updateEmployeeList.isEmpty()) {
            update updateEmployeeList;
        }
    }

    public void finish(Database.BatchableContext bc){

    }
}