force-app/main/default/objects/Budget__c/Budget__c.object-meta.xml
<CustomObject>
    <label>Budget</label>
    <nameField>
        <label>Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budget</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Budget__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>Budget</relationshipLabel>
    <relationshipName>Budget</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Budget__c/fields/Employees_Budget__c.field-meta.xml
<CustomField>
    <fullName>Employees_Budget__c</fullName>
    <label>Employees Budget</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Count_of_bugets__c.field-meta.xml
<CustomField>
    <fullName>Count_of_bugets__c</fullName>
    <label>Count of bugets</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Current_Company__c.field-meta.xml
<CustomField>
    <fullName>Current_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>Employee</relationshipLabel>
    <relationshipName>Employee</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BudgetTriggerHandler.cls
public with sharing class BudgetTriggerHandler {

    public void onAfterUpdate(Map<Id,Budget__c> newMap){
        setNewValueCountOfBugets(newMap);
        
        Set<Id> budgetIds = new Set<Id>(newMap.keyset());
        List<Employee__c> updateEmployeeList = [SELECT Count_of_bugets__c FROM Employee__c WHERE Current_Company__c IN (SELECT Company__c FROM Budget__c WHERE ID IN :budgetIds)];
        AggregateResult  maxvalue = [SELECT MAX(Employees_Budget__c) maxBudget FROM Budget__c WHERE Company__c IN (SELECT Current_Company__c FROM Employee__c WHERE id IN :updateEmployeeList)];
        
        for (Employee__c employee : updateEmployeeList) {
            employee.Max_Employee_Budget__c = (Decimal)maxvalue.get('maxBudget');
        }

        if (!updateEmployeeList.isEmpty()) {
            update updateEmployeeList;
        }
    }

    public void onAfterInsert(Map<Id,Budget__c> newMap){
        setNewValueCountOfBugets(newMap);
    }

    public void onAfterDelete(Map<Id,Budget__c> newMap){
        setNewValueCountOfBugets(newMap);
    }
    
    private void setNewValueCountOfBugets(Map<Id,Budget__c> newMap){
        Set<Id> budgetIds = new Set<Id>(newMap.keyset());
        List<Employee__c> updateEmployeeList = [SELECT Count_of_bugets__c FROM Employee__c WHERE Current_Company__c IN (SELECT Company__c FROM Budget__c WHERE ID IN :budgetIds)];
        Integer count = database.countQuery('SELECT COUNT() FROM Budget__c WHERE Company__c IN (SELECT Current_Company__c FROM Employee__c WHERE id IN :updateEmployeeList)');
        
        for (Employee__c employee : updateEmployeeList) {
            employee.Count_of_bugets__c = count;
        }

        if (!updateEmployeeList.isEmpty()) {
            update updateEmployeeList;
        }
    }
}